const KEY='coi-breeders-v1';let state=JSON.parse(localStorage.getItem(KEY)||'null')||{dogs:[],litters:[],current:null};const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='archive')renderArchive();if(id==='new')renderPedigreeInputs();window.scrollTo(0,0)}
function field(id,ph){return '<div class="tree-node"><input data-node="'+id+'" placeholder="'+ph+'" /></div>'}
function renderPedigreeInputs(){const levels=['Padre/Madre','Nonni','Bisnonni','Trisnonni','Quadrisnonni'];document.getElementById('sireTree').innerHTML=levels.map((g,i)=>'<div class="gen-title">'+g+'</div>'+Array.from({length:2**Math.min(i,3)},(_,j)=>field('s'+i+'_'+j,'Nome antenato')).join('')).join('');document.getElementById('damTree').innerHTML=levels.map((g,i)=>'<div class="gen-title">'+g+'</div>'+Array.from({length:2**Math.min(i,3)},(_,j)=>field('d'+i+'_'+j,'Nome antenato')).join('')).join('')}
function getTree(prefix){const out={};document.querySelectorAll('[data-node^="'+prefix+'"]').forEach(e=>{if(e.value.trim())out[e.dataset.node]=e.value.trim()});return out}
function ancestors(tree,prefix){const map={};Object.entries(tree).forEach(([k,v])=>{const m=k.match(/^[sd](\d+)_/);if(!m)return;const gen=+m[1];if(gen===0)return;map[v]=(map[v]||[]).concat(gen+1)});return map}
function calculate(){const sire=document.getElementById('sireName').value.trim(),dam=document.getElementById('damName').value.trim();if(!sire||!dam){alert('Inserisci almeno il nome del padre e della madre.');return}const st=getTree('s'),dt=getTree('d'),sa=ancestors(st,'s'),da=ancestors(dt,'d'),common=Object.keys(sa).filter(x=>da[x]);let total=0,details=[];common.forEach(a=>{sa[a].forEach(n1=>da[a].forEach(n2=>{const c=Math.pow(.5,n1+n2+1);total+=c;details.push({a,n1,n2,c})})});const litter={id:crypto.randomUUID(),name:document.getElementById('litterName').value||'Analisi senza nome',sire,dam,coi:total,common,details,created:new Date().toISOString()};state.current=litter;state.litters.unshift(litter);save();renderResult(litter);showView('result')}
function renderResult(r){document.getElementById('resultTitle').textContent=r.name;document.getElementById('coiValue').textContent=(r.coi*100).toFixed(3)+'%';document.getElementById('coiNote').textContent=r.common.length?'Calcolato sui percorsi genealogici disponibili.':'Nessun antenato comune rilevato nel pedigree inserito.';document.getElementById('commonCount').textContent=r.common.length;document.getElementById('ancestors').innerHTML=r.common.length?r.common.map(a=>'<div class="ancestor"><b>'+esc(a)+'</b><span>'+r.details.filter(x=>x.a===a).length+' percorso/i</span></div>').join(''):'<div class="empty">Nessun antenato comune nei dati inseriti.</div>';document.getElementById('calculationDetails').innerHTML=r.details.slice(0,30).map(x=>'<div class="formula">'+esc(x.a)+': (1/2)^('+x.n1+' + '+x.n2+' + 1) = '+(x.c*100).toFixed(3)+'%</div>').join('')||'<div class="empty">Nessun contributo da mostrare.</div>'}
function addDog(){const name=prompt('Nome del cane');if(!name)return;state.dogs.push({id:crypto.randomUUID(),name});save();renderArchive()}
function renderArchive(){document.getElementById('dogCount').textContent=state.dogs.length;document.getElementById('litterCount').textContent=state.litters.length;document.getElementById('dogs').innerHTML=state.dogs.length?state.dogs.map(d=>'<div class="ancestor"><b>'+esc(d.name)+'</b><button class="danger" onclick="removeDog(\''+d.id+'\')">Elimina</button></div>').join(''):'<div class="empty">Nessun cane archiviato.</div>';document.getElementById('litters').innerHTML=state.litters.length?state.litters.map((r,i)=>'<div class="ancestor"><div><b>'+esc(r.name)+'</b><br><small>'+esc(r.sire)+' × '+esc(r.dam)+'</small></div><b>'+((r.coi||0)*100).toFixed(3)+'%</b></div>').join(''):'<div class="empty">Nessuna analisi salvata.</div>'}
function removeDog(id){state.dogs=state.dogs.filter(x=>x.id!==id);save();renderArchive()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function printReport(){window.print()}
document.getElementById('dogCount').textContent=state.dogs.length;document.getElementById('litterCount').textContent=state.litters.length;if(state.current)renderResult(state.current);renderPedigreeInputs();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();const b=document.getElementById('install');b.classList.remove('hidden');b.onclick=()=>e.prompt()});
